version: '3.8'

services:
  database:
    image: postgres:15-alpine
    container_name: speedball-db
    environment:
      POSTGRES_DB: speedball_hub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secure_password_change_me}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - speedball-network
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: speedball-backend
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:${DB_PASSWORD:-secure_password_change_me}@database:5432/speedball_hub
      SESSION_SECRET: ${SESSION_SECRET:-change-this-in-production}
      PORT: 5000
    depends_on:
      - database
    networks:
      - speedball-network
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: speedball-frontend
    environment:
      NODE_ENV: production
    networks:
      - speedball-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: speedball-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
      - certbot_data:/var/www/certbot
    depends_on:
      - frontend
      - backend
    networks:
      - speedball-network
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: speedball-certbot
    volumes:
      - certbot_data:/var/www/certbot
      - ./ssl:/etc/letsencrypt
    command: certonly --webroot --webroot-path=/var/www/certbot --email admin@rowad.com --agree-tos --no-eff-email --force-renewal -d rowad.speedballhub.com
    depends_on:
      - nginx

volumes:
  postgres_data:
  certbot_data:

networks:
  speedball-network:
    driver: bridge

