
services:
  database:
    image: postgres:15-alpine
    container_name: speedball-db-dev
    environment:
      POSTGRES_DB: speedball_hub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - speedball-network
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: speedball-app-dev
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:password@database:5432/speedball_hub
      SESSION_SECRET: dev-secret-key-change-in-production
      PORT: 8000
    ports:
      - '3000:3000' # Frontend
      - '8000:8000' # Backend
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/frontend/node_modules
      - /app/apps/backend/node_modules
      - /app/apps/frontend/.next
    depends_on:
      - database
    networks:
      - speedball-network
    command: npm run dev

volumes:
  postgres_data_dev:

networks:
  speedball-network:
    driver: bridge
